<?php
/*
----------------------------------------
Copyright (c) 2025 - Vai-Natura
----------------------------------------
File    : block_my_account.php
Purpose : Personal-account popup — lets the currently signed-in user
          edit their own profile information without leaving the page.

Modal layout, opened by clicking the user block (.bando-user) in the
top header (which include() this file at render time).

Included from header.php, which is itself rendered by pages that have
already called application_top.php. We therefore reuse the globals
that application_top sets up:
  - $id_user             — session-resolved current user id
  - $login_user / $email_user / $prenom_user / $nom_user / $info_user
                         — session-cached user fields
  - $sql_link            — open DB connection
  - $languages_array     — supported languages
  - $_SESSION['csrf_token'] — generated by any admin page; we generate
                              it here as a fallback for the (rare) case
                              where the user opens the popup before
                              visiting an admin page.

Editable fields:
  - Last name        (nom)
  - First name       (prenom)
  - Additional info  (info)
  - Language         (lang)

Read-only fields (intentionally displayed but locked):
  - Login            (login)        — identity, must remain stable
  - Email            (email)        — used for password reset etc.
  - Service          (id_service)   — assigned by admins only

The save endpoint (process_my_account_save.php) ignores any attempt to
post the read-only fields, so a manually crafted request can't escape
the restriction client-side.
----------------------------------------
*/

// CSRF token — reuse the one already in session if present; create a
// new one only if no other admin page has done so. Single source of
// truth shared with process_my_account_save.php's verification.
if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

// Service label — application_top doesn't load it (no need on most
// pages), so we do a tiny lookup here for the read-only display.
$myacc_service_label = '';
if (isset($id_service_user) && (int) $id_service_user > 0)
{
    $sv_query = tep_db_query(
        $sql_link,
        "SELECT name, description FROM " . TABLE_SERVICE
        . " WHERE id_service = " . (int) $id_service_user . " LIMIT 1"
    );
    $sv_tab = tep_db_fetch_array($sv_query);
    if ($sv_tab)
    {
        $myacc_service_label = html_entity_decode($sv_tab['name'] ?? '');
        if (!empty($sv_tab['description']))
        {
            $myacc_service_label .= ' - ' . html_entity_decode($sv_tab['description']);
        }
    }
}

// Login / email / language — application_top's getAdminInfo() exposes
// nom / prenom / info but the contents of $tab_session for the other
// fields is implementation-dependent (changed across versions of the
// helper). To stay safe we re-read these three values straight from
// TABLE_USER here. Same connection, single row, negligible cost.
$myacc_login = '';
$myacc_email = '';
$myacc_lang  = LANGUAGE_TERRITOIRE;

if (isset($id_user) && (int) $id_user > 0)
{
    $u_query = tep_db_query(
        $sql_link,
        "SELECT login, email, lang FROM " . TABLE_USER
        . " WHERE id = " . (int) $id_user . " LIMIT 1"
    );
    $u_tab = tep_db_fetch_array($u_query);
    if ($u_tab)
    {
        $myacc_login = html_entity_decode($u_tab['login'] ?? '');
        $myacc_email = html_entity_decode($u_tab['email'] ?? '');
        if (!empty($u_tab['lang']))
        {
            $myacc_lang = $u_tab['lang'];
        }
    }
}
?>

<div id='block_my_account'
     style='display:none;position:fixed;top:0;left:0;width:100vw;height:100vh;
            background:rgba(0,0,0,0.4);z-index:2500;'>

    <!-- Inner wrapper: absolutely centered via top/left + transform.
         More robust than display:flex on the overlay because the
         overlay's display value gets swapped between 'none' and 'block'
         by JS — transform-based centering is independent of the
         parent's display mode. -->
    <div style='position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);
                background:#FBF9F1;border-radius:6px;width:540px;max-width:92vw;
                max-height:90vh;overflow-y:auto;
                box-shadow:0 8px 24px rgba(0,0,0,0.3);font-family:inherit;'>

        <!-- Header -->
        <div style='background:#176B87;color:#fff;padding:12px 16px;
                    display:flex;align-items:center;justify-content:space-between;'>
            <span style='font-size:15px;font-weight:bold;'>
                <?php echo TEXT_MYACC_TITLE; ?>
            </span>
            <span id='myacc_close' style='cursor:pointer;font-size:20px;line-height:1;'
                  title='<?php echo TEXT_BTN_CANCEL; ?>'>&times;</span>
        </div>

        <!-- Inline feedback banner -->
        <div id='myacc_info' style='display:none;margin:10px 14px;padding:8px 12px;
                                    border-radius:3px;font-size:13px;'></div>

        <!-- Form body -->
        <form id='formMyAccount' style='padding:14px 18px;font-size:13px;'>

            <input type='hidden' name='csrf_token'
                   value='<?php echo htmlspecialchars($_SESSION['csrf_token'], ENT_QUOTES); ?>'>

            <!-- id_user_agent: lets the server cross-check that the
                 posted user matches the session-resolved one. Even
                 if a malicious client overrides this value, the
                 server will reject any id that does NOT match the
                 session, so this is purely an extra layer (defence
                 in depth) on top of the CSRF token. -->
            <input type='hidden' name='id_user_agent'
                   value='<?php echo (int) $id_user; ?>'>

            <table style='width:100%;border-collapse:collapse;'>

                <!-- Login (read-only) -->
                <tr>
                    <td style='padding:6px 0;width:140px;color:#666;'>
                        <?php echo TEXT_US_F1_LOGIN_LABEL; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <span style='font-weight:bold;color:#333;'>
                            <?php echo htmlspecialchars($myacc_login, ENT_QUOTES); ?>
                        </span>
                        <span style='margin-left:6px;color:#999;font-style:italic;font-size:11px;'>
                            (<?php echo TEXT_MYACC_LOCKED; ?>)
                        </span>
                    </td>
                </tr>

                <!-- Email (read-only) -->
                <tr>
                    <td style='padding:6px 0;color:#666;'>
                        <?php echo TEXT_US_F1_MAIL_LABEL; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <span style='color:#333;'>
                            <?php echo htmlspecialchars($myacc_email, ENT_QUOTES); ?>
                        </span>
                        <span style='margin-left:6px;color:#999;font-style:italic;font-size:11px;'>
                            (<?php echo TEXT_MYACC_LOCKED; ?>)
                        </span>
                    </td>
                </tr>

                <!-- Service (read-only) -->
                <tr>
                    <td style='padding:6px 0;color:#666;'>
                        <?php echo TEXT_US_LIST_COL_FROM; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <span style='color:#333;'>
                            <?php echo htmlspecialchars($myacc_service_label, ENT_QUOTES); ?>
                        </span>
                        <span style='margin-left:6px;color:#999;font-style:italic;font-size:11px;'>
                            (<?php echo TEXT_MYACC_LOCKED; ?>)
                        </span>
                    </td>
                </tr>

                <tr><td colspan='2'><hr style='border:0;border-top:1px solid #ddd;margin:8px 0;'></td></tr>

                <!-- Last name (editable) -->
                <tr>
                    <td style='padding:6px 0;color:#444;font-weight:bold;'>
                        <?php echo TEXT_US_F1_NOM_LABEL; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <input type='text' name='nom' id='myacc_nom'
                               value='<?php echo htmlspecialchars($nom_user, ENT_QUOTES); ?>'
                               style='width:280px;'>
                    </td>
                </tr>

                <!-- First name (editable) -->
                <tr>
                    <td style='padding:6px 0;color:#444;font-weight:bold;'>
                        <?php echo TEXT_US_F1_PRENOM_LABEL; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <input type='text' name='prenom' id='myacc_prenom'
                               value='<?php echo htmlspecialchars($prenom_user, ENT_QUOTES); ?>'
                               style='width:280px;'>
                    </td>
                </tr>

                <!-- Additional info (editable) -->
                <tr>
                    <td style='padding:6px 0;color:#444;font-weight:bold;vertical-align:top;'>
                        <?php echo TEXT_US_F1_INFO_LABEL; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <textarea name='info_user' id='myacc_info_user'
                                  style='width:280px;height:60px;'><?php echo htmlspecialchars($info_user, ENT_QUOTES); ?></textarea>
                    </td>
                </tr>

                <!-- Language (editable) -->
                <tr>
                    <td style='padding:6px 0;color:#444;font-weight:bold;'>
                        <?php echo TEXT_US_F1_LANG_LABEL; ?>
                    </td>
                    <td style='padding:6px 0;'>
                        <select name='lang' id='myacc_lang' style='width:290px;'>
                            <?php
                            foreach ($languages_array as $code => $label) {
                                $selected = ($code == $myacc_lang) ? 'selected' : '';
                                echo "<option value='" . htmlspecialchars($code, ENT_QUOTES) . "' " . $selected . ">"
                                   . htmlspecialchars($label, ENT_QUOTES) . "</option>";
                            }
                            ?>
                        </select>
                    </td>
                </tr>

            </table>

            <!-- Action buttons -->
            <div style='display:flex;justify-content:flex-end;gap:8px;margin-top:18px;'>
                <button type='button' id='myacc_cancel' class='button_close' style='width:120px;'>
                    <?php echo TEXT_BTN_CANCEL; ?>
                </button>
                <button type='button' id='myacc_save'   class='button'       style='width:140px;'>
                    <?php echo TEXT_STATION_EDIT_SAVE; ?>
                </button>
            </div>

        </form>

    </div>
</div>


<script>
    // -----------------------------------------------
    // Personal-account popup — open / close / save handlers
    //
    // Lifecycle:
    //  - .bando-user (in header.php) has an onClick that calls
    //    openMyAccount() — defined here so the wiring stays in one place.
    //  - The popup uses display:flex when visible to center its child;
    //    swapped back to display:none when closed.
    //  - Save POSTs to process_my_account_save.php and refreshes the
    //    header text (name / role) on success without a page reload.
    //
    // The DOM lookups all happen inside the handlers (not at load time)
    // because this block can be included before some of the referenced
    // elements have been rendered. Defensive null-checks throughout.
    // -----------------------------------------------

    (function() {

        var modal       = document.getElementById('block_my_account');
        var closeBtn    = document.getElementById('myacc_close');
        var cancelBtn   = document.getElementById('myacc_cancel');
        var saveBtn     = document.getElementById('myacc_save');
        var infoBanner  = document.getElementById('myacc_info');
        var form        = document.getElementById('formMyAccount');

        if (!modal) { return; }

        // -----------------------------------------------
        // openMyAccount() / closeMyAccount()
        // Exposed on window so the header onClick can find them.

        window.openMyAccount = function() {
            // Clear any stale feedback from a previous open
            if (infoBanner) {
                infoBanner.style.display = 'none';
                infoBanner.innerHTML     = '';
            }
            // 'block' is enough — the inner card centers itself via
            // top/left + transform, independent of the overlay's display.
            modal.style.display = 'block';
            // Focus first editable field for a quicker edit flow
            var firstField = document.getElementById('myacc_nom');
            if (firstField) { firstField.focus(); }
        };

        window.closeMyAccount = function() {
            modal.style.display = 'none';
        };


        // -----------------------------------------------
        // Close interactions

        if (closeBtn)  { closeBtn.addEventListener('click',  window.closeMyAccount); }
        if (cancelBtn) { cancelBtn.addEventListener('click', window.closeMyAccount); }

        // Click on the dark overlay (but NOT on the inner card) closes too
        modal.addEventListener('click', function(e) {
            if (e.target === modal) { window.closeMyAccount(); }
        });

        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape' && modal.style.display !== 'none') {
                window.closeMyAccount();
            }
        });


        // -----------------------------------------------
        // Save handler

        function showBanner(msg, isError) {
            if (!infoBanner) { return; }
            infoBanner.innerHTML        = msg;
            infoBanner.style.border     = isError ? '2px solid #930000' : '2px solid #09886d';
            infoBanner.style.background = isError ? '#fdecec'           : '#ecf7ef';
            infoBanner.style.color      = isError ? '#930000'           : '#0a7d34';
            infoBanner.style.display    = 'block';
        }

        function refreshHeaderUser() {
            // Soft-update the user block in the top header so the
            // freshly saved name appears immediately, without a reload.
            var nom    = document.getElementById('myacc_nom').value.trim();
            var prenom = document.getElementById('myacc_prenom').value.trim();
            var info   = document.getElementById('myacc_info_user').value.trim();

            var nameEl = document.querySelector('.bando-user .name');
            var roleEl = document.querySelector('.bando-user .role');
            if (nameEl) { nameEl.textContent = (prenom + ' ' + nom).trim(); }
            if (roleEl) { roleEl.textContent = info; }

            // Avatar initials — first letter of first + last name
            var avatarEl = document.querySelector('.bando-user .avatar');
            if (avatarEl) {
                var ip = (prenom.charAt(0) || '').toUpperCase();
                var in_ = (nom.charAt(0) || '').toUpperCase();
                avatarEl.textContent = ip + in_;
            }
        }

        if (saveBtn) {
            saveBtn.addEventListener('click', function() {
                if (!form) { return; }

                // Disable button to prevent double-submit
                saveBtn.disabled = true;
                saveBtn.style.opacity = '0.6';
                saveBtn.style.cursor = 'wait';

                var formData = new FormData(form);

                var xhr = new XMLHttpRequest();
                xhr.open('POST', 'include/structure/admin/process_my_account_save.php', true);

                xhr.onreadystatechange = function() {
                    if (xhr.readyState !== 4) { return; }

                    // Re-enable the button no matter what
                    saveBtn.disabled = false;
                    saveBtn.style.opacity = '';
                    saveBtn.style.cursor = '';

                    if (xhr.status === 200) {
                        try {
                            var r = JSON.parse(xhr.responseText);
                            showBanner(r.msg_info || '', !!r.erreur);

                            if (!r.erreur) {
                                refreshHeaderUser();
                                // If the language changed, reload the page so
                                // the new translations apply throughout the UI.
                                if (r.lang_changed) {
                                    setTimeout(function() {
                                        window.location.reload();
                                    }, 1200);
                                }
                            }
                        } catch (e) {
                            showBanner('<?php echo TEXT_MYACC_ERR_UNEXPECTED; ?>', true);
                        }
                    } else {
                        showBanner('<?php echo TEXT_MYACC_ERR_HTTP; ?> ' + xhr.status, true);
                    }
                };

                xhr.send(formData);
            });
        }

    })();
</script>